// generated by stringer -type itemType; DO NOT EDIT

package parse

import "fmt"

const _itemType_name = "itemErroritemObjNameitemDotitemFunctionitemLeftBraceitemFnArgumentitemRightBraceitemLeftCurlyitemFieldNameitemCommaitemRightCurlyitemEOF"

var _itemType_index = [...]uint8{0, 9, 20, 27, 39, 52, 66, 80, 93, 106, 115, 129, 136}

func (i itemType) String() string {
	if i < 0 || i+1 >= itemType(len(_itemType_index)) {
		return fmt.Sprintf("itemType(%d)", i)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
